version: "2"

services:
  mariadb-backup:
    image: ghcr.io/bugfender/mariadb-backup-s3:10.11
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_HOST=mysql
      - S3_BUCKET_NAME=
      - S3_ENDPOINT=s3.eu-west-1.amazonaws.com
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=eu-west-1
      - WAIT_SECONDS=86400
      - RETENTION_DAYS=30
  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: example
